
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[317] =
    {   0,
        0,    0,   74,   74,    5,    5,   11,   11,   83,   81,
       79,   80,    4,   81,   81,   72,   59,   59,   59,   59,
       59,   55,   72,   59,   59,   59,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   59,
       60,   73,   74,   75,   82,   76,    5,    8,    9,    7,
       11,   10,   12,   78,   77,   78,   78,    0,    0,    0,
        3,    0,    0,    0,   69,   71,   70,   63,   57,   56,
       67,    0,   55,    0,   61,   62,    0,   65,   66,   58,
       64,   54,   54,   54,   54,   54,   54,   23,   25,   28,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   45,   54,   54,   54,   54,   54,   68,   74,
        6,    5,   11,   77,   77,   78,   55,   78,   55,    1,
        3,    0,    3,    0,    0,    1,    0,    0,    0,    0,
        0,   56,    0,    0,    0,    0,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   32,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,    0,
       56,   78,   56,    2,    2,    0,    0,    0,    0,    0,
       14,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   36,   37,

       54,   54,   40,   54,   54,   54,   54,   46,   54,   54,
       49,   54,   54,   54,   78,   56,    0,    0,    0,   13,
       15,   54,   17,   54,   19,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   52,   54,   54,   54,   54,   39,
       54,   54,   54,   44,   54,   48,   50,   51,   54,   54,
       54,   54,   54,   22,   54,   54,   54,   26,   54,   54,
       54,   54,   35,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   33,   54,
       54,   54,   54,   43,   47,   54,   16,   18,   20,   54,
       54,   54,   24,   27,   29,   34,   54,   54,   42,   54,

       21,   54,   54,   54,   54,   53,   54,   54,   54,   41,
       30,   31,   54,   54,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   22,   23,   23,   24,   25,   26,
       27,   28,    1,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   39,   40,   41,   42,
       36,   43,   44,   45,   46,   47,   36,   48,   36,   49,
       50,   51,   52,   53,   36,    1,   54,   55,   56,   57,

       58,   59,   60,   36,   61,   36,   36,   62,   63,   64,
       65,   66,   36,   67,   68,   69,   70,   71,   36,   72,
       36,   73,   74,   75,   76,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    6,    1
    } ;

static const flex_int16_t yy_base[329] =
    {   0,
        0,    0,   75,   76,   79,   83,   87,   88,  275, 1001,
     1001, 1001, 1001,   77,   91, 1001,  258,  256,   74,  110,
      215,  139,  238,   93,  188,  187,    0,   76,  125,   82,
      125,  145,  102,   54,  121,  147,  148,  149,  154, 1001,
      198, 1001,    0, 1001, 1001, 1001, 1001, 1001, 1001,  214,
        0,    0, 1001,    0,  207,  208,  270,  200,  197,  266,
      193,  216,  224,  241, 1001, 1001, 1001, 1001, 1001,  299,
     1001,  233,  323,  337, 1001, 1001,  142, 1001, 1001, 1001,
     1001,    0,  107,  238,  318,  324,  241,  334,  229,    0,
      240,  247,  268,  270,  247,  279,  280,  306,  310,  327,

      364,  330,  330,  341,  342,  335,  351,  336, 1001,    0,
     1001,  192,    0,  192,    0,  415,  424,  462,  131, 1001,
     1001,  174,  140,  432,  515, 1001,  440,  448,  481,  137,
      487,  507,  401,  110,   75,  108,  346,  357,  371,  446,
      452,  446,  475,  502,  510,  502,  517,  511,  509,    0,
      523,  516,  511,  518,  531,  530,  527,  527,  530,  531,
      545,  547,  549,  546,  555,  553,  558,  555,  565,  593,
      608,  620,   63, 1001, 1001,  628,  647,  663,   77,   76,
      109,  574,  576,  620,  609,  640,  630,  646,  658,  655,
      652,  648,  660,  658,  661,  667,  660,  668,    0,    0,

      674,  668,    0,  667,  667,  671,  680,    0,  690,  702,
        0,  707,  695,  710,  749,  757,   93,  774,   89, 1001,
     1001,  728,    0,  714,    0,  720,  734,  744,  743,  747,
      742,  756,  767,  755,    0,  760,  759,  762,  772,    0,
      772,  762,  771,    0,  770,    0,    0,    0,  782,  776,
      784,  770,  780,    0,  793,  796,  800,    0,  801,  806,
      797,  809,    0,  804,  805,  803,  805,  808,  817,  811,
      811,  814,  811,  826,  829,  821,  822,  824,    0,  824,
      832,  843,  836,    0,    0,  838,    0,    0,    0,  850,
      848,  846,    0,    0,    0,    0,  852,  856,    0,  853,

        0,  855,  852,  865,  871,    0,  862,  870,  866,    0,
        0,    0,  862,  870,    0, 1001,  935,  941,  947,  953,
      959,   90,  965,  970,  976,  982,  988,  994
    } ;

static const flex_int16_t yy_def[329] =
    {   0,
      316,    1,  317,  317,  318,  318,  319,  319,  316,  316,
      316,  316,  316,  320,  321,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  316,
      316,  316,  323,  316,  316,  316,  316,  316,  316,  316,
      324,  324,  316,  320,  325,  320,  320,  326,  326,  326,
      316,  326,  326,  326,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  327,  316,  316,  316,
      316,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  316,  323,
      316,  316,  324,  325,  328,  320,  320,  320,   57,  316,
      316,  326,  316,  326,  326,  316,  326,  326,  326,  326,
      316,  316,  327,  316,  316,  316,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  316,
      320,  320,  118,  316,  316,  326,  326,  326,  316,  316,
      316,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  320,  320,  326,  326,  326,  316,
      316,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,    0,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316
    } ;

static const flex_int16_t yy_nxt[1079] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   16,   17,
       18,   16,   19,   20,   21,   22,   22,   22,   22,   22,
       22,   22,   22,   23,   16,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   27,   27,   27,   27,   33,   27,
       34,   35,   36,   37,   38,   27,   39,   27,   27,   40,
       41,   40,   10,   27,   28,   29,   30,   31,   32,   27,
       27,   27,   33,   27,   34,   35,   36,   37,   38,   27,
       39,   27,   27,   42,   16,   10,   40,   44,   44,   45,
       45,   48,   55,   49,   50,   48,   67,   49,   50,   52,
       52,   53,   53,   59,   82,  174,   60,   61,   97,  174,

      135,   68,  136,  221,  220,   76,   62,   62,   63,   64,
       64,   64,   64,   64,   88,  172,   83,   56,   77,   78,
       79,   84,   97,   69,   57,   70,   70,   70,   70,   70,
       70,   70,   70,  135,  135,  181,  181,  180,   95,   88,
       83,   56,   96,  174,  134,   84,  175,  137,   57,   98,
       46,   46,   72,   85,   73,   73,   73,   73,   73,   73,
       73,   73,   95,   99,   89,   86,   96,  135,   90,  136,
       87,  137,   91,   92,   98,  100,  102,  105,   85,  101,
      174,   93,  107,  172,  103,  106,  108,   99,   89,   86,
       94,   74,   90,  104,   87,  115,   91,  170,   92,  121,

      100,  102,  105,  121,  101,   93,  120,  107,  103,  106,
      115,  108,  109,   81,   94,   80,  111,  104,  112,  112,
      112,  116,  126,  117,  117,  117,  117,  117,  117,  117,
      126,  127,  127,  127,  127,  127,  127,  127,  127,  128,
      128,  128,  128,  128,  129,  130,  130,  126,   70,   70,
       70,   70,   70,   70,   70,   70,  130,  130,  130,  130,
      130,  130,  130,  130,   75,   71,   66,   65,  138,  143,
      122,  122,  123,  147,  316,  316,  316,  112,  316,  152,
      112,  148,  112,  118,  149,  119,  119,  119,  119,  119,
      119,  119,  119,  138,  143,  316,  316,  147,  119,  119,

      119,  119,  119,  119,  152,  148,  124,  150,  149,  151,
      153,  316,  316,  125,   70,   70,   70,   70,   70,   70,
       70,   70,  154,  119,  119,  119,  119,  119,  119,  122,
      124,  150,  122,  151,  122,  153,   72,  125,   73,   73,
       73,   73,   73,   73,   73,   73,  154,  131,  155,  131,
      156,   74,  132,  132,  132,  132,  132,  132,  132,  132,
      139,  140,  141,  142,  144,  316,  157,  162,  316,  163,
      164,  165,  155,  316,  156,   74,  166,  145,  169,  316,
      146,  167,  316,  182,  139,  140,  141,  142,  168,  144,
      157,  162,  158,  163,  183,  164,  165,  159,  160,  184,

      166,  145,  169,  316,  146,  161,  167,  182,  316,  316,
      316,  316,  168,  316,  316,  316,  316,  158,  183,  316,
      316,  316,  159,  160,  184,  316,  316,  316,  179,  161,
      171,  171,  171,  171,  171,  171,  171,  116,  121,  117,
      117,  117,  117,  117,  117,  117,  174,  176,  177,  177,
      177,  176,  176,  176,  174,  130,  130,  130,  130,  130,
      130,  130,  130,  122,  122,  122,  122,  122,  122,  122,
      122,  316,  316,  316,  316,  316,  172,  173,  173,  173,
      173,  173,  173,  173,  173,  316,  185,  174,  186,  187,
      173,  173,  173,  173,  173,  173,  122,  122,  122,  122,

      122,  122,  132,  132,  132,  132,  132,  132,  132,  132,
      185,  316,  186,  187,  188,  173,  173,  173,  173,  173,
      173,  121,  132,  132,  132,  132,  132,  132,  132,  132,
      178,  178,  178,  178,  178,  178,  178,  178,  188,  189,
      190,  316,  191,  178,  178,  178,  178,  178,  178,  192,
      316,  194,  195,  196,  316,  197,  198,  193,  199,  200,
      201,  202,  204,  189,  203,  190,  191,  205,  178,  178,
      178,  178,  178,  178,  192,  194,  195,  206,  196,  197,
      198,  193,  199,  207,  200,  201,  202,  204,  203,  208,
      209,  205,  210,  211,  212,  213,  214,  112,  112,  112,

      316,  316,  206,  316,  316,  316,  222,  207,  223,  316,
      316,  316,  316,  208,  209,  316,  210,  211,  212,  213,
      316,  214,  316,  171,  171,  171,  171,  171,  171,  171,
      215,  222,  215,  223,  174,  216,  216,  216,  216,  216,
      216,  216,  216,  217,  217,  217,  217,  217,  217,  217,
      224,  316,  225,  174,  316,  316,  112,  316,  316,  112,
      172,  112,  218,  218,  218,  218,  218,  218,  218,  174,
      316,  316,  226,  316,  227,  224,  225,  228,  219,  219,
      219,  219,  219,  219,  219,  219,  229,  230,  316,  231,
      232,  219,  219,  219,  219,  219,  219,  226,  227,  233,

      234,  235,  228,  236,  237,  238,  239,  316,  240,  241,
      242,  229,  230,  231,  232,  243,  219,  219,  219,  219,
      219,  219,  244,  233,  234,  235,  245,  236,  237,  238,
      246,  239,  240,  241,  242,  247,  316,  248,  249,  243,
      316,  316,  316,  316,  316,  316,  244,  316,  316,  316,
      245,  316,  316,  316,  316,  246,  250,  316,  251,  252,
      247,  248,  253,  249,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      174,  250,  251,  252,  254,  255,  256,  253,  257,  217,
      217,  217,  217,  217,  217,  217,  258,  259,  316,  260,

      261,  262,  263,  264,  265,  316,  266,  267,  254,  255,
      256,  268,  257,  269,  316,  270,  271,  316,  272,  273,
      258,  274,  259,  260,  261,  262,  263,  275,  264,  265,
      266,  267,  276,  277,  278,  268,  279,  280,  269,  270,
      281,  271,  272,  273,  282,  283,  274,  284,  285,  286,
      316,  287,  275,  288,  289,  290,  291,  276,  277,  278,
      279,  292,  280,  293,  281,  294,  295,  296,  282,  283,
      297,  284,  285,  298,  286,  287,  299,  288,  289,  290,
      300,  291,  301,  316,  302,  303,  292,  293,  304,  294,
      295,  296,  305,  306,  297,  307,  308,  309,  298,  310,

      299,  311,  312,  316,  300,  313,  314,  301,  302,  303,
      315,  316,  304,  316,  316,  316,  305,  306,  316,  307,
      308,  316,  309,  316,  310,  311,  316,  312,  316,  313,
      314,  316,  316,  316,  315,   43,   43,   43,   43,   43,
       43,   47,   47,   47,   47,   47,   47,   51,   51,   51,
       51,   51,   51,   54,  316,  316,   54,   54,   54,   58,
       58,   58,   58,   58,   58,  110,  316,  110,  316,  110,
      113,  113,  113,  316,  113,  113,  114,  316,  114,  114,
      114,  114,   59,   59,   59,   59,   59,   59,  133,  133,
      133,  133,  133,  133,  115,  316,  115,  115,  115,  115,

        9,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316
    } ;

static const flex_int16_t yy_chk[1079] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,    5,   14,    5,    5,    6,   19,    6,    6,    7,
        8,    7,    8,   15,  322,  219,   15,   15,   34,  217,

      135,   19,  135,  180,  179,   24,   15,   15,   15,   15,
       15,   15,   15,   15,   30,  173,   28,   14,   24,   24,
       24,   28,   34,   20,   14,   20,   20,   20,   20,   20,
       20,   20,   20,  136,  181,  136,  181,  134,   33,   30,
       28,   14,   33,  130,   77,   28,  123,   83,   14,   35,
        3,    4,   22,   29,   22,   22,   22,   22,   22,   22,
       22,   22,   33,   35,   31,   29,   33,   77,   31,   77,
       29,   83,   31,   32,   35,   36,   37,   38,   29,   36,
      122,   32,   39,  119,   37,   38,   39,   35,   31,   29,
       32,   22,   31,   37,   29,  114,   31,  112,   32,   61,

       36,   37,   38,   59,   36,   32,   58,   39,   37,   38,
       55,   39,   41,   26,   32,   25,   50,   37,   50,   50,
       50,   56,   62,   56,   56,   56,   56,   56,   56,   56,
       63,   62,   62,   62,   62,   62,   62,   62,   62,   63,
       63,   63,   63,   63,   63,   63,   63,   64,   72,   72,
       72,   72,   72,   72,   72,   72,   64,   64,   64,   64,
       64,   64,   64,   64,   23,   21,   18,   17,   84,   87,
       60,   60,   60,   89,    9,    0,    0,   50,    0,   95,
       50,   91,   50,   57,   92,   57,   57,   57,   57,   57,
       57,   57,   57,   84,   87,    0,    0,   89,   57,   57,

       57,   57,   57,   57,   95,   91,   60,   93,   92,   94,
       96,    0,    0,   60,   70,   70,   70,   70,   70,   70,
       70,   70,   97,   57,   57,   57,   57,   57,   57,   60,
       60,   93,   60,   94,   60,   96,   73,   60,   73,   73,
       73,   73,   73,   73,   73,   73,   97,   74,   98,   74,
       99,   70,   74,   74,   74,   74,   74,   74,   74,   74,
       85,   85,   86,   86,   88,    0,  100,  102,    0,  103,
      104,  105,   98,    0,   99,   73,  106,   88,  108,    0,
       88,  107,    0,  137,   85,   85,   86,   86,  107,   88,
      100,  102,  101,  103,  138,  104,  105,  101,  101,  139,

      106,   88,  108,  133,   88,  101,  107,  137,    0,    0,
        0,    0,  107,    0,    0,    0,    0,  101,  138,    0,
        0,    0,  101,  101,  139,    0,  133,    0,  133,  101,
      116,  116,  116,  116,  116,  116,  116,  117,  124,  117,
      117,  117,  117,  117,  117,  117,  127,  124,  124,  124,
      124,  124,  124,  124,  128,  127,  127,  127,  127,  127,
      127,  127,  127,  128,  128,  128,  128,  128,  128,  128,
      128,    0,    0,    0,    0,    0,  117,  118,  118,  118,
      118,  118,  118,  118,  118,    0,  140,  129,  141,  142,
      118,  118,  118,  118,  118,  118,  129,  129,  129,  129,

      129,  129,  131,  131,  131,  131,  131,  131,  131,  131,
      140,    0,  141,  142,  143,  118,  118,  118,  118,  118,
      118,  125,  132,  132,  132,  132,  132,  132,  132,  132,
      125,  125,  125,  125,  125,  125,  125,  125,  143,  144,
      145,    0,  146,  125,  125,  125,  125,  125,  125,  147,
        0,  148,  149,  151,    0,  152,  153,  147,  154,  155,
      156,  157,  159,  144,  158,  145,  146,  160,  125,  125,
      125,  125,  125,  125,  147,  148,  149,  161,  151,  152,
      153,  147,  154,  162,  155,  156,  157,  159,  158,  163,
      164,  160,  165,  166,  167,  168,  169,  170,  170,  170,

        0,    0,  161,    0,    0,    0,  182,  162,  183,    0,
        0,    0,    0,  163,  164,    0,  165,  166,  167,  168,
        0,  169,    0,  171,  171,  171,  171,  171,  171,  171,
      172,  182,  172,  183,  176,  172,  172,  172,  172,  172,
      172,  172,  172,  176,  176,  176,  176,  176,  176,  176,
      184,    0,  185,  177,    0,    0,  170,    0,    0,  170,
      171,  170,  177,  177,  177,  177,  177,  177,  177,  178,
        0,    0,  186,    0,  187,  184,  185,  188,  178,  178,
      178,  178,  178,  178,  178,  178,  189,  190,    0,  191,
      192,  178,  178,  178,  178,  178,  178,  186,  187,  193,

      194,  195,  188,  196,  197,  198,  201,    0,  202,  204,
      205,  189,  190,  191,  192,  206,  178,  178,  178,  178,
      178,  178,  207,  193,  194,  195,  209,  196,  197,  198,
      210,  201,  202,  204,  205,  212,    0,  213,  214,  206,
        0,    0,    0,    0,    0,    0,  207,    0,    0,    0,
      209,    0,    0,    0,    0,  210,  222,    0,  224,  226,
      212,  213,  227,  214,  215,  215,  215,  215,  215,  215,
      215,  215,  216,  216,  216,  216,  216,  216,  216,  216,
      218,  222,  224,  226,  228,  229,  230,  227,  231,  218,
      218,  218,  218,  218,  218,  218,  232,  233,    0,  234,

      236,  237,  238,  239,  241,    0,  242,  243,  228,  229,
      230,  245,  231,  249,    0,  250,  251,    0,  252,  253,
      232,  255,  233,  234,  236,  237,  238,  256,  239,  241,
      242,  243,  257,  259,  260,  245,  261,  262,  249,  250,
      264,  251,  252,  253,  265,  266,  255,  267,  268,  269,
        0,  270,  256,  271,  272,  273,  274,  257,  259,  260,
      261,  275,  262,  276,  264,  277,  278,  280,  265,  266,
      281,  267,  268,  282,  269,  270,  283,  271,  272,  273,
      286,  274,  290,    0,  291,  292,  275,  276,  297,  277,
      278,  280,  298,  300,  281,  302,  303,  304,  282,  305,

      283,  307,  308,    0,  286,  309,  313,  290,  291,  292,
      314,    0,  297,    0,    0,    0,  298,  300,    0,  302,
      303,    0,  304,    0,  305,  307,    0,  308,    0,  309,
      313,    0,    0,    0,  314,  317,  317,  317,  317,  317,
      317,  318,  318,  318,  318,  318,  318,  319,  319,  319,
      319,  319,  319,  320,    0,    0,  320,  320,  320,  321,
      321,  321,  321,  321,  321,  323,    0,  323,    0,  323,
      324,  324,  324,    0,  324,  324,  325,    0,  325,  325,
      325,  325,  326,  326,  326,  326,  326,  326,  327,  327,
      327,  327,  327,  327,  328,    0,  328,  328,  328,  328,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "simplon.l"
#line 2 "simplon.l"
#include <stdio.h>
#include "simplon.tab.h"

int linea = 1;
#line 793 "lex.yy.c"

#line 795 "lex.yy.c"

#define INITIAL 0
#define COM 1
#define CAD 2
#define CADERR 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 22 "simplon.l"


#line 25 "simplon.l"
 /* Caracteres */
#line 1020 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1001 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "simplon.l"
{ printf("linea %d, caracter: %s\n", linea, yytext); return(CTC_CARACTER); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "simplon.l"
{ printf("linea %d, caracter: %s\n", linea, yytext); return(CTC_CARACTER); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 28 "simplon.l"
printf ("linea %d, ERROR: %s\n",linea,yytext);
	YY_BREAK
/* Cadenas */
case 4:
YY_RULE_SETUP
#line 31 "simplon.l"
{ printf("linea %d, cadena: ", linea); yymore(); BEGIN (CAD); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "simplon.l"
{ yymore(); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 33 "simplon.l"
{ yymore(); linea++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "simplon.l"
BEGIN (CADERR);
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 35 "simplon.l"
{ linea++; BEGIN (CADERR); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "simplon.l"
{ printf("%s\n", yytext); BEGIN 0; return (CTC_CADENA); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 37 "simplon.l"
linea++;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 38 "simplon.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "simplon.l"
{ printf ("\nlinea %d, ERROR en cadena\n",linea); BEGIN 0; }
	YY_BREAK
/* Modulos */
case 13:
YY_RULE_SETUP
#line 42 "simplon.l"
{ printf("linea %d, librería: %s\n", linea, yytext); return (NOMBRE_MODULO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "simplon.l"
printf ("linea %d, ERROR: %s\n",linea,yytext);
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 44 "simplon.l"
{ printf ("linea %d, ERROR\n",linea); linea++; }
	YY_BREAK
/* Palabras reservadas */
case 16:
YY_RULE_SETUP
#line 47 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(BOOLEANO); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(BUCLE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(CARACTER); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(CASOS); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(COMIENZO); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(CONSTANTE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(CUANDO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(DE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(DEVOLVER); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(EN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(ENTERO); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(ENTONCES); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(ES); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(EXPORTAR); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(DECLARACION); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(DESCENDENTE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(FIN); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(FUNCION); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(MIENTRAS); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(MODULO); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(OTRO); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(PARA); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 69 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(PROCEDIMIENTO); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 70 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(RANGO); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 71 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(REAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 72 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(REFERENCIA); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(REGISTRO); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 74 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(REPETIR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 75 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(SALIR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 76 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(SI); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 77 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(SINO); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 78 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(SUBTIPO); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 79 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(TABLA); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 80 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(TIPO); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(VACIA); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(VALOR); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(FALSO); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "simplon.l"
{ printf("linea %d, palabra reservada: %s\n", linea, yytext); return(VERDADERO); }
	YY_BREAK
/* Identificadores */
case 54:
YY_RULE_SETUP
#line 87 "simplon.l"
{ printf("linea %d, identificador: %s\n", linea, yytext); return (IDENTIFICADOR); }	
	YY_BREAK
/* Numeros */
case 55:
YY_RULE_SETUP
#line 90 "simplon.l"
{ printf("linea %d, ctc entera: %s\n", linea, yytext); return(CTC_ENTERA); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "simplon.l"
{ printf("linea %d, ctc real: %s\n", linea, yytext); return(CTC_REAL); }
	YY_BREAK
/* Operadores */
case 57:
YY_RULE_SETUP
#line 94 "simplon.l"
{ printf("linea %d, operador: %s\n", linea, yytext); return(PUNTOS); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "simplon.l"
{ printf("linea %d, operador: %s\n", linea, yytext); return(FLECHA); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 96 "simplon.l"
{ printf("linea %d, operador: %s\n", linea, yytext); return(yytext[0]); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 97 "simplon.l"
{ printf("linea %d, operador: %s\n", linea, yytext); return(RESTO); }
	YY_BREAK
/* Delimitadores */
case 61:
YY_RULE_SETUP
#line 100 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(ASIGNACION); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(DESP_IZDA); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(DESP_DCHA); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(GEQ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(LEQ); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(NEQ); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(AND); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(OR); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(POTENCIA); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(DEC); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 110 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(INC); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 111 "simplon.l"
{ printf("linea %d, delimitador: %s\n", linea, yytext); return(yytext[0]); }
	YY_BREAK
/* Comentarios */
case 73:
YY_RULE_SETUP
#line 114 "simplon.l"
BEGIN (COM);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "simplon.l"
;
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 116 "simplon.l"
linea++;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "simplon.l"
BEGIN 0;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "simplon.l"
;
	YY_BREAK
/* Espacios, saltos de linea y errores */
case 78:
YY_RULE_SETUP
#line 121 "simplon.l"
printf ("linea %d, ERROR: %s\n",linea,yytext);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "simplon.l"
;
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 123 "simplon.l"
linea++;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "simplon.l"
printf ("linea %d, ERROR: %s\n",linea,yytext);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 126 "simplon.l"
ECHO;
	YY_BREAK
#line 1510 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
case YY_STATE_EOF(CAD):
case YY_STATE_EOF(CADERR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 316);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 126 "simplon.l"


